import re

import time

import sys

from pdjus.dal.ParteDistribuicaoDao import ParteDistribuicaoDao


class ClassificaParteDistribuicao:
    def __init__(self):
        self.parte_distribuicao_dao = ParteDistribuicaoDao()
        self.regex_pessoa_juridica_1 = re.compile('(ADAMANTINA|AGUAS DA PRATA|AGUAS DE LINDOIA|AGUAS DE SANTA BARBARA|AGUAS DE SAO PEDRO|ALTINOPOLIS|ALTO ALEGRE|ALVINLANDIA|AMERICANA|AMERICO BRASILIENSE|ANALANDIA|ANDRADINA|APARECIDA D OESTE|ARACARIGUAMA|ARACATUBA|ARACOIABA DA SERRA|ARARAQUARA|ARCO IRIS|AREIOPOLIS|AURIFLAMA|AVANHANDAVA|BADY BASSITT|BARAO DE ANTONINA|BARRA BONITA|BARRA DO CHAPEU|BARRA DO TURVO|BEBEDOURO|BENTO DE ABREU|BIRITIBA MIRIM|BOA ESPERANCA DO SUL|BOM JESUS DOS PERDOES|BOM SUCESSO DE ITARARE|BRAGANCA PAULISTA|BREJO ALEGRE|BURITIZAL|CABRALIA PAULISTA|CACHOEIRA PAULISTA|CAFELANDIA|CAMPINA DO MONTE ALEGRE|CAMPO LIMPO PAULISTA|CAMPOS DO JORDAO|CAMPOS NOVOS PAULISTA|CANDIDO RODRIGUES|CAPAO BONITO|CAPELA DO ALTO|CARAGUATATUBA|CARAPICUIBA|CASA BRANCA|CASSIA DOS COQUEIROS|CATANDUVA|CERQUILHO|CHARQUEADA|CHAVANTES|CORDEIROPOLIS|CORONEL MACEDO|CORUMBATAI|COSMOPOLIS|COSMORAMA|CRISTAIS PAULISTA|DESCALVADO|DIVINOLANDIA|DOIS CORREGOS|DOLCINOPOLIS|EMBU GUACU|EMILIANOPOLIS|ENGENHEIRO COELHO|ESPIRITO SANTO DO PINHAL|ESPIRITO SANTO DO TURVO|ESTIVA GERBI|ESTRELA D OESTE|ESTRELA DO NORTE|EUCLIDES DA CUNHA PAULISTA|FERNANDOPOLIS|FLORA RICA|FLORIDA PAULISTA|GENERAL SALGADO|GUARANI D OESTE|GUARARAPES|GUARATINGUETA|GUARULHOS|GUATAPARA|GUZOLANDIA|HERCULANDIA|HORTOLANDIA|IBIRAREMA|IGARACU DO TIETE|IGARAPAVA|ILHA COMPRIDA|ILHA SOLTEIRA|INDAIATUBA|INDIAPORA|INUBIA PAULISTA|IRACEMAPOLIS|ITAPECERICA DA SERRA|ITAPETININGA|ITAPIRAPUA PAULISTA|ITAPORANGA|ITAQUAQUECETUBA|ITIRAPINA|ITUVERAVA|JABORANDI|JABOTICABAL|JACUPIRANGA|JAGUARIUNA|JARDINOPOLIS|JERIQUARA|JOANOPOLIS|JUNQUEIROPOLIS|JUQUITIBA|LARANJAL PAULISTA|LAVRINHAS|LENCOIS PAULISTA|LUCIANOPOLIS|MAIRINQUE|MAIRIPORA|MARABA PAULISTA|MARAPOAMA|MARIAPOLIS|MARINOPOLIS|MARTINOPOLIS|MERIDIANO|MESOPOLIS|MIGUELOPOLIS|MINEIROS DO TIETE|MIRA ESTRELA|MIRANDOPOLIS|MIRANTE DO PARANAPANEMA|MIRASSOLANDIA|MOGI DAS CRUZES|MOGI GUACU|MOGI MIRIM|MONTE ALEGRE DO SUL|MONTE ALTO|MONTE APRAZIVEL|MONTE AZUL PAULISTA|MONTE CASTELO|MONTE MOR|MORRO AGUDO|MORUNGABA|MURUTINGA DO SUL|NARANDIBA|NATIVIDADE DA SERRA|NAZARE PAULISTA|NEVES PAULISTA|NHANDEARA|NOVA ALIANCA|NOVA CAMPINA|NOVA CANAA PAULISTA|NOVA CASTILHO|NOVA EUROPA|NOVA GRANADA|NOVA GUATAPORANGA|NOVA INDEPENDENCIA|NOVA LUZITANIA|NOVA ODESSA|NOVO HORIZONTE|NUPORANGA|ONDA VERDE|ORINDIUVA|OURO VERDE|PALESTINA|PALMARES PAULISTA|PALMEIRA D OESTE|PARAGUACU PAULISTA|PARAIBUNA|PARANAPANEMA|PARANAPUA|PARIQUERA ACU|PATROCINIO PAULISTA|PAULICEIA|PAULISTANIA|PAULO DE FARIA|PEDRA BELA|PEDRANOPOLIS|PEDREGULHO|PEDRINHAS PAULISTA|PENAPOLIS|PEREIRA BARRETO|PILAR DO SUL|PINDAMONHANGABA|PINDORAMA|PINHALZINHO|PIQUEROBI|PIRACICABA|PIRAPORA DO BOM JESUS|PIRAPOZINHO|PIRASSUNUNGA|PIRATININGA|PITANGUEIRAS|PONTALINDA|PONTES GESTAL|PORANGABA|PORTO FELIZ|PORTO FERREIRA|POTIRENDABA|PRADOPOLIS|PRAIA GRANDE|PRESIDENTE ALVES|PRESIDENTE BERNARDES|PRESIDENTE EPITACIO|PRESIDENTE PRUDENTE|PRESIDENTE VENCESLAU|PROMISSAO|RANCHARIA|REDENCAO DA SERRA|REGENTE FEIJO|REGINOPOLIS|RIBEIRAO BONITO|RIBEIRAO BRANCO|RIBEIRAO CORRENTE|RIBEIRAO DO SUL|RIBEIRAO DOS INDIOS|RIBEIRAO GRANDE|RIBEIRAO PIRES|RIBEIRAO PRETO|RINOPOLIS|RIO CLARO|RIO DAS PEDRAS|RIO GRANDE DA SERRA|RIOLANDIA|SALESOPOLIS|SALMOURAO|SALTO DE PIRAPORA|SALTO GRANDE|SANTA ADELIA|SANTA ALBERTINA|SANTA BARBARA D OESTE|SANTA BRANCA|SANTA CLARA D OESTE|SANTA CRUZ DA CONCEICAO|SANTA CRUZ DA ESPERANCA|SANTA CRUZ DAS PALMEIRAS|SANTA CRUZ DO RIO PARDO|SANTA ERNESTINA|SANTA FE DO SUL|SANTA GERTRUDES|SANTA ISABEL|SANTA LUCIA|SANTA MARIA DA SERRA|SANTA MERCEDES|SANTA RITA D OESTE|SANTA RITA DO PASSA QUATRO|SANTA ROSA DO VITERBO|SANTA SALETE|SANTANA DA PONTE PENSA|SANTANA DO PARNAIBA|SANTO ANASTACIO|SANTO ANDRE|SANTO ANTONIO DA ALEGRIA|SANTO ANTONIO DE POSSE|SANTO ANTONIO DO ARACANGUA|SANTO ANTONIO DO JARDIM|SANTO ANTONIO DO PINHAL|SANTO EXPEDITO|SANTOPOLIS DO AGUAPEI|SAO BENTO DO SAPUCAI|SAO BERNARDO DO CAMPO|SAO CAETANO DO SUL|SAO CARLOS|SAO FRANCISCO|SAO JOAO DA BOA VISTA|SAO JOAO DAS DUAS PONTES|SAO JOAO DE IRACEMA|SAO JOAO DO PAU D ALHO|SAO JOAQUIM DA BARRA|SAO JOSE DA BELA VISTA|SAO JOSE DO BARREIRO|SAO JOSE DO RIO PARDO|SAO JOSE DO RIO PRETO|SAO JOSE DOS CAMPOS|SAO LOURENCO DA SERRA|SAO LUIS DO PARAITINGA|SAO MANUEL|SAO MIGUEL ARCANJO|SAO PAULO|SAO PEDRO DO TURVO|SAO ROQUE|SAO SEBASTIAO DA GRAMA|SAO SEBASTIAO|SAO SIMAO|SAO VICENTE|SEBASTIANOPOLIS DO SUL|SERRA AZUL|SERRA NEGRA|SERTAOZINHO|SETE BARRAS|SILVEIRAS|SUD MENNUCCI|SUZANAPOLIS|TABATINGA|TABOAO DA SERRA|TAPIRATIBA|TAQUARITINGA|TAQUARITUBA|TAQUARIVAI|TERRA ROXA|TORRE DE PEDRA|TRES FRONTEIRAS|TUPI PAULISTA|TURMALINA|UNIAO PAULISTA|VALPARAISO|VARGEM GRANDE DO SUL|VARGEM GRANDE PAULISTA|VARZEA PAULISTA|VIRADOURO|VISTA ALEGRE DO ALTO|VITORIA BRASIL|VOTORANTIM|VOTUPORANGA)',re.S)

        self.regex_pessoa_juridica_2 = re.compile('((INDUSTRIA|MOTOBOY|PIZZA|SOCIEDADE|VIDRACARIA|EXTREMO SUL|MARMOR?ARIA|UNIMED|HOPI\s*HARI|LICEU CORACAO DE JESUS|OLE BRASIL FC|ARQ BELLI|ORDEM AUXILIADORA|PRESBITERIAN[OA]|EXPERTS?|MASTERCARD|CHOPERIA|\sLAR\s|LUMINARIA(S)?|RENOVAR|VARIEDADES|IGREJA|\sAUTO\s|EDIFIC((ACOES)|(IO))|COMUNIDADE|FACAS|PERNAMBUCANAS|AMERICANAS|HSBC|PONTO\s*FRIO|BANCO|FACTORING|ARREND|FINANC(EIRO)?|SEGURO|SEGURADORA|CONSORCIO|CREDITO|LEASING|INVEST|CORRETORA|\\bCRED\\b|CRED\s+FIN|ASSET|BANK|MERCANTIL)|FOMENTO|EMPRESTIMO|FINASA|TERRESTR|CREDICARD|SECURIT|C\s+F\s+I|ABN\s+AMRO|HSBC\s+BANK|CITICORP|BRADESCO|CAIXA\s+ECONOMICA|PANAMERICANO\s+SA|TRADING|PARTICIPAC(OES)?|(CAPITALIZA|DISTRIBUIDORA\s+DE\s+TITULO(S)?|CREDINORTE|CREDREAL\\b|BANESPA|BANERJ|ARAUCARIA\s+CORRET|DOURADA\s+CORCAMBIO|CAMBIO\s+E\s+VALOR(ES)?|BOVESPA)|(INSS|IAPAS\\b|SINDICATO|\\bS?IND\.?\\b|SIND\.|SEM\s+TERRA|\\bMST\\b|EMPRESA|PLATAFORMA|ACADEMICO|AQUECEDOR|HEATING|FOOD|SABESP)|(OXIGENIO|MONTAGE(M|NS)|TECNIC[OA]|DIOCES(E|ANA)|CALHA(S)?|DOCE(S)?|SANEAMENTO|MERCADINHO|PARTIDO|\\bESCOLAS?\\b|LICENCIAMENTO|LOTERICA|ITAUCARD|IAUTEC|^GRUPO)|(LTD|CIA\.|COMPANHIA|COMPONENTE|C[\.\s]*P[\.\s]*F[\.\s]*L|REPRESENTA|NEGOCIO(S)?|IMP\.|EXP\.|IMPORTACAO|EXPORTACAO|INCORP|PROMOC|\\bLANCHE(S)?\\b|RESTAUR|DISTRIBUI|SERVICO|ORG\.|CINEMA|EXPRESS|DELIVERY)|(COMERCI|PRODU(C|T)|CONDOMINIO|SOCIEDADE|CONJUNTO|REGISTR|CARTORIO|JUSTICA|OFICIAL|IMOBILIARI[OA])|(\\bMODAS?\\b|MANUTENCAO|FUNDACAO|PAPEL|FRIGORIF|CARNES?\\b|FRUTA|HORTIF|FATURA|LIMITADA|SOC\.|ART\.|EMP\.|ASSESSOR|COBRANCA|TIPOGRAFIA|GRAFIC?A)|(\\bACAO\\b|CONCRETO|EMPREIT|\\bOBRAS?\\b|RECURSOS\s+HUMANOS?|SISTEMA|EMPREEND(IMENTO(S?))?|LABORAT(OR)?(IO)?|ADM\.?(IN)?\s+\.?(ISTR)?|VEICULO|INTERMED|TERRAPL([EA]NAGEM)?|MEDIC[A|O]|S\/C|CABELEREIRO|MANICURE|COIFFURE|INTERACTIVE|SERV\.|PROGRAMA|TREINAMENTO|RAPIDO|METODO|DIAGNOST|CONFERENCIA|SYSTEM|SOLUTION|\&|\\bCIA\\b|\\bMIDIA?S?\\b|INTEGRA|LANGUAGE|DIRECAO|INTERATIVA|REPOUSO|CARREGAMENT|INSTITU|RETIFICA|LIMPADORA|DESENHO|HOUSE|SINTESE|FISIOTER|\\bUNIDAS\\b|\\bPLANEJ\\b|INTEGRAL|OFTALMO|IDIOMA(S)?|REPOUSO|^(CASA|SANTA)|\\bBENS\\b|LOTEAMENTO|NUCLEO|DESPACHANTE|TREINAMENTO|URBANISMO|POUSADA|AQUATICA|PORTARIA|GRUPAMENTO|VEICULO|EMPREGO|ESTUDO|BRASILEIR|MECANIC|BRINQUEDO|SOFTWARE|QUALITY|LIVRARIA|DISTRIB|COMUNICA|DIVERSO(ES)?|ENTRETEN|MERCADO|MEDICO|ENCOMENDA|AUDITOR|ECONOM|INFORMA|CONTINENT|SIDERURG)|(TRUST|LOGISTICA|GLENCORE\s+GRAIN\s+BV|SCHOOL|^PAPER|\\bPAPER|MANAGEMENT|AIRLINE|PARTNER|TECHNOLOGY|SUDIO|PHONE|ENTERTAINMENT)|(ADVENTURE|AGENCIA|STORAGE|SHIP|SPECIAL|ESTRANGEIRA|NETWORK|PROGRESS|PORTALCOMEX|SINCRONIA|DOMESTICA|RASTREAM|ORIGINAL|CARDIOVASC)|(HIDR|TITULO|ALARMES?|JURIDIC[OA]|OPERACIONAL|SONY\s+ERICSSON|\\bMUNDO\\b|ESTETICA|ANIMAL|CIRURG|ODONTO|ICATU\s+HARTFORD|WH.RPOOL|OCULOS|MICRO)|(ADVOGADO|EQUIP|ACUSTICO|BOOKING|WATER\s+PARK|^CIA_ISOLAMENTO|LAYOUT|PINTURA|TRADICIONA|FOTOGRAF|MOLDURA|FITNESS|BASICA|MEDICINA|MERCHAND)|(CONSULT|LINHAS?\\b|AMERICAN|INSTRUM|\\bGRAOS?\\b|TECIDOS?|COSMET|BENEFICIAMENTO|ESPORT|PAINEIS?|ESTRUT|VIACAO|MANUTEN|SERVIC)|(HOLDING|AUTOM|HIDRA|TELEF|INC\.|CORP|FERROV|ALCOOL|FUMO|TABACO|ALIMENTO|PROPAGANDA|ECAD|\\bCLUB\\b|MASSA\s+FALIDA|SERVICOS?|TELEFONICA|INSTALAC(AO|OES))|(PROJETOS?|MARITIMOS?|AUTO\s+VIACAO|LOCACAO|DROGARIA|TRANSPORT|UNIMED|ENTERPRISE|PROMO|RESIDENCIA(S|IS|L)?|COMPUTA|MARKET|BUSINESS|COMPRA|WORLD|\\bINTER\\b)|(LUBRIFIC|EDIF.*RESID|\\bCURSOS?\\b|FUTEBOL|\\bAGRO\\b|SERASA|GERENCIA|TV|TELEVISAO|RADIO|SOLUCOES|HOTEL|REFRI|MOTORES|HIPOTECA)|(EVENTO?S?|OLEOS?|IMPRESS|ESTACIONAMENTO|ALUMINIO|LLC|TRATORES|OPTICAL|FRANCHISING|FERRAMENTAS?|PRESIDENTE)|(LIMITED|CONCESSIONARIA|ACUCAR|CACA\s+E\s+PESCA|FARMACIA|HORTIGRANGEIROS|LANCHONETE|SUPRIMENTOS?|MERCEARIA|JORNA(IS|L)|DIGITAL|COUROS)|(DESENTUPIDORA|CEREAIS|ROUPA|TINTAS?\\b|CAFE(EIRA)?|ROLAMENTOS?|BILHAR|SERRALHERIA|COUROS\s+ME|PNEUS?|SORVETES)|(SAPATO|CALCADO|TEXTIL|GESSO|SALGADOS|BAZAR|ACOUGUE|MEDICAMENTOS?|ARTESIANOS?|ADUBO|FERTILIZANTE|DISCOS?|PURIFICADORES|DOMESTICOS?|GAZETA)|(COML\s+REPRE|COMBUSTIV|ESTUDIO|AEROLINEAS|IND\s+DE|INDDE|GRAVACOES|RELOGIO|ESQUADRIAS?|DEDETIZADORA|EMBALAGENS|PISOS)|(PLANTAS?|MONTAGENS|DECORACOES|APARELHOS?|PRESENTES?|PAPEIS|\\bCIMENTO|TRIBUNA|FOGOS|COLETES|VAN(AT)JOSA|CHURRASCARIA|LOCACOES|SORVETERIA|ABATEDOURO)|(\\bPOSTOS?\\b|NAVEGACAO|TORNEARIA|FUNILARIA|TERCEIRIZACAO|CABINES\s+ESPECIAIS|MUSCULOS\s+E|FUNERARIOS|FUNERARIA|PISCINAS?|MARMORES\s+E\s+GRANIT|CONS\s+E\s+EMPREN|CONFEITARIA)|(ADV\s+ASSOCIADOS|VIDEO\s+MIX|SHIPPING|LTRDA|ORNAMENTAIS|EMPACOTAMENTO|ENS\s+DE\s+IDIOMAS?|ADVASSOCIADOS|PIZZARIA|TERRAPL[AE]NAGEM|CARROCERIAS)|(\\bLT|LTEIF|LTAIF|ALLPAPER|MADEIREIRA|FLORESTAL|ATACAD|DEPOSIT|GARAGEM|INDCOM|REPCOM|COML|\\bUNI\\b|\\bASSOC|SERVCOM|EXPIMP|IMPEXP|IMPOR)|(EXPOR|INTERN|ACIDENTES|ORTOPEDICO|ARMAZEN|KARAMAZEN|LAVANDERIA|PROCESS|PLASTICOS?|OFICINA|CONSER|ELEVADORES|RODONORTE|LOJA|MAGAZINE|VENDAS?|DESENV)|(COMISS|SEGURANCA|TECELAGEM|TEC\s+BRAS|TECHNOLOGIA|VALORES|CVM|INVESTIG|PARQUE|ROTISSERI)|(REVESTIMENTO|PADARIA|ANDAIMES|CENTRO|USINA|CONGREGACAO|ASSOCIACAO|UMBANDA|ASSOC\.|CONSELHO|CONFEDERA|COOP|\\bCLUBE\\b|RESORT|ADVOCACIA)|(TELECOM|SUPPLY|GREMIO|EDUCA|APOIO|QUIMI|CONS\.|FUND\.|\\bCOND\\b|PESQUISA|FACULDADE|UNIVERS|DIRETORIO|FEDERACAO|TRANSPLANTE)|(RURAL|ORGANIZA|REGIONAL|INSTITUTO|PROCON|ANEXOS?|EDIFICIO|INMETRO|CONJ\s+MORAD|CONJ\s+RESID|ACADEMIA|TABELI)|(COPIADORA|NACIONAL|\s+DO\s+BRASIL|NOME\s+FANTASIA|HOSPIT|TEMPLO|CULTUR|ASSOCIACAO\s+ATLETICA|ASSOCBRASDE|ASSOCCRISTA)|(DIVISORIAS?|AMIGA?OS?|SICREDI|ENTIDADE|BENEF|I\s+A\s+P\s+A\s+S|CREA|FAZENDA\s+PUBLICA|FAZENDA\s+ESTADUAL|FAZENDA\s+MUNICIPAL|FAZENDA\s+NACIONAL)|(FAZENDA|PUB|GOVERNO|A\s+UNIAO|\\bIBAMA\\b|ESTADO\s+DO\s+PARANA|REFORMA|DEPARTAMENTO|DEP(\.|ART)\.?|DEPTO)|(MUNIC(IPIO)?|PREFEITURA|MUNICIP|\\bFAZ\\b|MINISTERIO|\\bCIDADE\\b|ESTADO|UNIAO|FEDERAL|AGENTE|TRANSITO|PREFEITO)|(O\s+JUIZO|ESTE\s+JUIZO|CORREIOS|VEREADORES|AMBIENTE|COMARCA|\\bVARA\\b|OFICIO|FISCA|JUIZO|RECEITA|PREFEIT|LICITACAO)|(EDICOES|CENTER|ROTISSERIA|FRETAMEN|CIRETRAN|ARBITRAGEM|POLICIAL|2\s+CI|2\s+DRDI|SECRET))',re.S)

        self.regex_pessoa_juridica_3 = re.compile('((MO?LLER.*MAERSK|EQUIPAMENT|RODAGEM|POLICIA\\b|COMANDANTE|EDITORA|CONDOMNIO|SUPERINT|DELEGADO|\\bMP\\b|MINISTERIO\s+PUBLICO)|(ME\s+E\s+OUTRO|\\bABATE\\b|ACABAMENTOS?|ACESSORIOS?|\\bACO\\b|ACUMULADORES|ADMINISTRACAO|ADMINISTRATIVAS?|ADMINISTRATIVO|AEREO)|(AERONAVES|AFINS|AGENCIAMENTO|AGENCIAS?|AGENTES?|AGRIC[OU]|\\bAGUAS?\\b|ALCOOLICAS?|ALIMENTACAO|ALIMENTAR|ALIMENTICIOS)|(ALIMENTOS?|ALOJAMENTO|AMBIENTAL|AMBULANTE|AMBULATORIAL|AMILACEOS|AMPLIFICACAO|ANALISES?|ANIMAIS|ANTERIORMENTE)|(APOSTAS?|AQUAVIARIOS?|AQUICULTURA|AREA|AREIA|ARGILA|\\bARMAS?\\b|ARMAZENAMENTO|ARQUITETURA|ARRENDAMENTO|\\bARTE\\b|ARTEFATOS)|(ARTIFICIAIS|ARTIGOS?|ARTISTICAS?|ASSINATURA|ASSISTENCIA|ASSOCIACOES|ASSOCIATIVAS?|ATENCAO|ATENDIMENTO|\s+ATIVIDADE)|(\s+ATIVIDADES?|ATIVOS?|\\bAUDIO|AUDITORIA|AUTOMOTORES|AUTOMOVEIS|AUXILIARES|\\bAZAR\\b|BATERIAS?|BEBIDAS?|BELICO|BIJUTERIA|BIOCOMBUSTIVEIS)|(BOMBAS?|BORRACHA|BRINQUEDOS?|BUFE|CABINES?|CABOTAGEM|CACA|CALCADOS?|CALDEIRARIA|CALDEIRAS?|CAMINHOES|CAMIONETAS?|CAPITALIZACAO)|(CAPTACAO|CARGA|\\bCARNE\\b|CARTAO|CARTOLINA|CARVAO|CATERING|CELULOSE|CENTRAL|CERAMICOS?|CERTIFICADAS?|CIENCIAS?|CIENTIFICAS)|(CINEMATOGRAFICAS?|CINEMATOGRAFICOS?|COLETA|COLETIVAS?|COLETIVOS?|COLHEITA|COMBATE|COMBINADOS?|COMBUSTIVEIS|COMERCIAIS|PLASTIC)|(COMERCIO|COMIDA|COMISSAO|COMPLEMENTACAO|COMPLEMENTAR|COMPONENTES?|COMPRESSORES|COMUNICACAO|COMUNICACAO|CONDICIONADO|CONDUTOR)|(CONFECC|CONSERVAS?|CONSTRUCAO|CONSTRUCOES|CONSULTORIA|CONSUMO|CONTABIL|CONTABILIDADE|CONTRATO|CONTROLE|CONTROLE|CONVALESCENTES|COQUERIAS)|(CORREIO|CORTICA|COSMETICOS?|COSTURA|COURO|CRONOMETROS?|CULTURAIS|CULTURAL|CURTIMENTO|CUTELARIA|\\bDADOS\\b|DECORACAO|DEFENSIVOS?|DEFESA|DEFICIENCIA)|(VAREJO|PLANEJA(M|D)|LABORATORIO|CELULAR|PANIFICA|ENXOVA|IRMANDADE|^IGREJA|^TEMPLO|COLEGIO|ADMINISTR|CLINIC|CONSTRUTORA)|(DEFICIENTES?|DEMOLICAO|DEPENDENCIA|DEPOSITOS?|DERIVADOS?|DESCARGA|DESCONTAMINACAO|DESDOBRAMENTO|DESIGN|DESINFESTANTES?|DETERGENTES?|DIAGNOSTICA)|(DIREITOS?|DISPOSICAO|DISTRIBUICAO|DISTURBIOS?|DIVERSOS|DOMESTICO|DOMISSANITARIOS|DUTOS|DUTOVIARIO|ECONOMICA|EDICAO|EDIFICIOS?|EDUCACAO)|(ELASTOMEROS|ELETRIC[AO](S)?|ELETRODOMESTICOS?|ELETROMEDICOS?|ELETRONIC|ELETROTERAPEUTICOS?|EMBARCACOES|EMPREENDIMENTOS)|(ENERGIA|ENGENHARIA|ENSINO|ENTREGA|EQUIPAMENTO|EQUIPAMENTOS?|ESCRITORIO|ESGOTO|ESMALTES?|ESPACIAL|ESPECIA(IS|LIZADOS|L)|(\\bBAR\\b))|(CHAPAS|ESPECIALIZADOS?|ESPECIFICAD[OA]S?|ESPECIFICO|ESPETACULOS?|ESPORTE|ESPORTIV[OA]S?|ESTAMPARIA|ESTRUTURA|ESTRUTURAS?|EVENTOS)|(EXECUTADAS|EXPERIMENTAL|EXPLORACAO|EXTRACAO|EXTRATERRITORIAIS|FABRICACAO|FARMACEUTICOS?|FARMOQUIMICOS?|FERRAGENS|FERRAMENTA|FERROLIGAS)|(FERROSOS|FERROVIARIOS?|FERROVIAS?|FIACAO|FIBRAS?|FIBROCIMENTO|FINANCEIROS?|FISICAS|FISICOS|FLORESTAS?|FLORICULTURA|FOGO|FORJARIA)|(FORNECIMENTO|FOTOGRAFIC[AO]S|FRUTAS|FUNDAMENTAL|FUNDICAO|FUNDOS|\\bGAS\\b|GASOSOS|GERACAO|GERADORES|\\bGERAL\\b|GESTAO|GORDURAS|GRAFICOS|GRAVACAO)|(GRAVADOS|GUSA|HIDRAULICAS|HIGIENE|HORTICULTURA|HOSPEDAGEM|HOTEIS|HUMAN[OA]S?|IDOSOS?|ILUMINACAO|IMOBILIARI[OA]S?|IMOVEIS)|(IMPRESSAO|IMUNODEPRIMIDOS|INCORPORACAO|INFANTIL|INFORMACAO|INFORMATICA|INFRA|INORGANICOS|INSTITUICOES|INSTRUMENTOS)|(INTANGIVEIS|INTEGRADA|INTERIOR|INTERIORES|INTERMEDIACAO|INTERNACIONAIS|INTERNET|INVESTIGACAO|INVESTIMENTO|IRRADIACAO|JOALHERIA|JOGOS|JORNAIS|JURIDICAS)|(CANTINA|LAMPADAS?|LATICINIOS?|LAVOURAS?|LAZER|LEGUMES|LIGADAS|LIMPEZA|LIVROS?|LOCAIS|MADEIRA|MAGNETICAS|MALHA|MALHARIA|MALOTE)|(REFRESCOS?|RENT\s+A\s+CAR|OFFICE|LOCADORA|FRENTE\s+DAS\s+MAES|LITORAL|TABLOIDE)|(MAQUINAS?|MARITIMO|MATERIAIS|MATERIAL|MATERIAS?|MEDICO|MEDICOS?|MEDIDA|\\bMEDIO|\\bMEIOS|MENTAL|METAIS|METAL|METALICAS?|METALICOS?|METALURGIA)|(METROFERROVIARIO|\\bMIDIAS?|MILITARES|MINERAIS|MINERAL|MINERIO|MOAGEM|MONETARIA|MONITORAMENTO|MOTOCICLETAS|MOVEIS|MUDAS|MUNICOES|MUSICA(IS|L)?)|(NATIVAS|NATURAIS|NATURAL|NIVEL|NOVOS|OBJETOS|\\bOBRA\\b|OBRIGATORIA|ODONTOLOGICO|ODONTOLOGOS|ONDULADO|ONIBUS|OPERADOR|OPERADORAS|OPERADORES)|(OPINIAO|OPTICAS|OPTICOS|ORGANICOS|ORGANISMOS|ORGANIZACAO|ORGANIZACOES|ORTOPEDICOS|PACIENTES|PAISAGISTICAS|PAPELAO|PARTES|TRANSP)|(PARTICIP|PARTICULAR|PARTICULARES|PASSAGEIROS|PASTAS|PATRIMONIO|PATRONAIS|PECAS|PECUARIA|PECUARIA;|PEDRAS|PERFUMARIA|PERIFERICOS)|(PERMANENTES|PESAD[AO]|PESCA(DO)?|PESQUISAS|PESSOAIS|PESSOAL|PETROLEO|PILHAS|PLANOS|PLANTADAS|PLASTICO|POLITICA|PORTADORES|PREPARACAO|PREPARACOES)|(PREPARADA|PREPARADOS|PRESERVACAO|PRESTACAO|PRESTADO|PREVIDEN|PRIMAS|PRINCIPALMENTE|PRIVADA|PROCESSAMENTO|PROFISSIONAIS)|(PROFISSIONAL|PROGRAMAS|PROPRIOS|PSICOSSOCIAL|PSIQUICOS|PUBLICA|PUBLICACOES|PUBLICIDADE|QUALQUER|QUENTE|QUIMIC[OA]|REBOQUES|RECEPCAO)|(RECONDICIONAMENTO|RECREACAO|RECREATIVOS|RECUPERACAO|RECURSOS|REDES|REFINO|RELACIONADAS|RELACIONADOS|RELOGIOS|REMOCAO|REPARACAO|REPRESENTANTES)|(RESERVAS|RESERVATORIOS|RESIDUOS|RESINAS|RESSEGUROS|RESTAURANTES|REVISTAS|RODOVIARIO|RODOVIAS|SABOES|SATELITE|SAUDE|SEDES)|(SEGURIDADE|SEGUROS|SELECAO|SEMELHANTES|SEMENTES|SIDERURGIA|SIMILARES|SINDICAIS|SINTETICAS|SISTEMAS|SOCIAIS|SOCIAL)|(SUPERIOR|SUPORTE|TANQUES|TECNICAS|TECNICO|TECNOLOGIA|TECNOLOGIAS|TECNOLOGICO|TELEATENDIMENTO|TELECOMUNICACOES|TELEFERICOS)|(TEMPORARIA|TEMPORARIAS|TERAPEUTICA|TERCEIROS|TERRENO|TERRESTRES|TESTE|TESTES|TEXTEIS|TINTAS|TIPOS|TORREFACAO|TRANCADO|TRANSFORMADORES|TRANSMISSAO)|(TRATAMENTO|TRENS|TRIBUTARIA|TRICOTAGEM|TUBOS|TURISMO|TURISTICOS|UNIDADES|URBANAS|URGENCIAS|\\bUSADOS?\\b|UTILITARIOS)|(VAPOR\\b|VAREJISTA|VEGETAIS|VEICULOS|VERNIZES|VESTUARIO|VETERINAR|VIAGE(M|NS)|\\bVIDA\\b|VIDEOS?|VIDRO|VIGILANCIA|VISTA|VIVOS|COMERCIO|\\bCONST\\b|COMERCIAL|\\bAGRIC\\b|COIFAS|\\bEIREL?LI\\b|\\bLDA\\b|IMPORTACAO|FOMENTO|CHEQUE|\\bLT\\b|COZINHAS|SAPATOS|ACIONAMENTOS|\\bCOMER\\b|CONFECCOES|\&|BC\s*ITAU|FISIOTERAPIA|AGENC\s*VIAG))',re.S)

        self.regex_pessoa_juridica_4 = re.compile("((\s+M\.?E\.?\\b)|[\-|\s+|\(]ME\)?\\b|L\s*?\.?T\s*?\.?D\s*?\.?A\\b\.?|S(\.|\/|\\\\)A|(M\s+?\.?E\s+?\.?I\b+?\.?)\\b|(\s+E\s*?\.?I\s*?\.?R\s*?\.?E\s*?\.?L\s*?\.?I\.?)|(\\bE\s+?\.?P\s+?\.?P\\b\.?)|(\-\s+M\.?E\.?\\b)|(\-?\s+?M\.?E\.?)\\b|(\s+E\.?P\.?P\.?\\b)|\sS\s?A\\b$)|\\bEIRELE\\b|\\b\d{11}\\b|\\bEPP\\b|\\bMEI\\b",re.S)

        self.regex_banco_1 = re.compile('BANC.|BANK',re.S)

        self.regex_banco_2 = re.compile(
            'BRASIL|NEON|INTER|RIBEIRAO|CETELEM|SEMEAR|B\.?M\.?\&FBOVESPA|RABOBANK|COOPERATIVO|BNP|KEB|CATERPILLAR|MORGAN|CNH|J.P|TOYOTA|ALFA|PSA|ABN|CARGILL|HONDA|BRADESCARD|INBURSA|BRADESCO|MONEO|KDB|TOP.ZIO|CSF|ORIGINAL|VIPAL|YAMAHA|AGIBANK|BANDEPE|RANDON|CONFIDENCE|FINAXIS|WESTERN|BBM|CAPITAL|WOORI|MERCANTIL|ITAUCARD|ITAU|TRIANGULO|KOMATSU|CBSS|ABC|BTG|MODAL|CLASSICO|GUANABARA|INDUSTRIAL|CEDULA|J.?P.?|RURAL|LOSANGO|CAIXA|CIT.BANK|RODOBENS|FATOR|ALVORADA|MAXIMA|IBM|ANDBANK|ITAULEASING|ARBI|TRICURY|VOLVO|SAFRA|INTERCAP|FIBRA|VOLKS(WAGEN)?|LUSO|GMAC|PAN|VOT.RANTIM|ITAUBANK|SUMITOMO|MERCEDES(\s*-?\s*BENZ)?|SOFISA|INDUSVAL|CREFISA|MIZUHO|INVESTCRED|BMG|BPN\s*BRASIL|CITIBNK|IATUBANK|S\.?C?HAH?IN|BANFORT|HSBC\s*BANK|UNI|B.LBAO|CREDICARD|BVA|FIAT|MULTIPLO|FRANCES|A\ ?B\ ?N AMRO|POT?TENCIAL|CREDI|CREDICARD|BCN|SANTOS|CACIQUE|CONTINENTAL|NACIONAL|BANKBOSTON|CREDIBEL|BANERJ|NOSSO|PARANA | ZOGBI|SCHHIN|FININVEST|FINASA|FICRISA|BRASIL S\/A|BMD|BANORTE|NOSSA C?A(IX|XI)A|S\/?\.?\ ?A$|HSBC..BANK BRASIL\ ? S\/?\.?A|^BNA?CO CITIBANK|^CAIXAO? ECONOMICA FEDERAL|^ A\.?B\.?[NM]\.?|^ CITICARD|(HA?SS?BC|H S (P|B) C)..?.?(BANC?K|BRASIL)|^ PROSPER|CITICARD|REAL|CREFISUL|BONSUCESSO|CITBANK|VEGA|BGN|UBS PACTUAL|B\.?C\.?N\.?|FICSA|SOCIETE|PAULISTA|PINE|DAYCOVAL|FIDIS|RCI|CIFRA|RENDIMENTO|BS2|OLE|CREDIT|SISTEMA|VR|OURINVEST|MAXINVEST|SANTAN..?ER|FORD|JOHN|A.J.|ORIGINAL',re.S)

        self.regex_banco_3 = re.compile('(ADM\.?(IN)?\.?(ISTRA)?(CAO|DORA)?\s?(DE)?\s?CART(AO|OES))|(CART(AO|OES)\s?DE\s?CREDITO)|(CART(AO|OES)\s?VISA)|(^CARTAO)|(AGENCIA\s?(DO)?\s?BANCO?(ARIA)?)|AMERICAN\sEXPRESS|BANESPA|UNIBANCO|FININ-?VEST|MASTERCARD|CREDICARD|CREDITOS?\s?IMOBILIARIO|HIPOTECARIA|FACTORING|FOMENTO\sMERCANTIL|FINANC(EIRA|IADORA)\s(ITAU|ALFA|ABN\sAYMORE|AMERICANAS|CACIQUE|CETELEM|CREFISA|BCN|BRADESCO)|ABN\sAMRO|ARR.*MERCANTIL|EMPRESTIMO|SECURIT|CRED(ITO)?.*FINAN(CIAMENTO)?|FINANCIAMENTO.*CRED(ITO)?|^FINANCEIRA|MAGAZINE\sLUIZA\sCREDITO',re.S)

        self.regex_pequena_empresa = re.compile('(\s+M\.?E\.?\s+)|(M\s+?\.?E\s+?\.?I\s+?\.?)$|((\s+|\-|\.)E\s+?\.?P\s+?\.?P\s+?\.?)|(\-\s+M\.?E\.?\s+)|(\-?\s+?M\.?E\.?)$|(\s+E\.?P\.?P\.?\s+)|(ME\s+E\s+OUTRO)|MICRO EMPRESA',re.S)

        self.regex_governo = re.compile('FAZ\.?(ENDA)? (ESTAD(O|UAL)|MUNICIP(IO|AL)|FEDERAL|NACIONAL|PUBLICA|GOVERNO)|A?\s?UNIAO$|ESTADO\s?D[OE]?\s?SAO\s?PAULO|SPPREV|^SUS|SISTEMA UNICO DE SAUDE|MESA DIRETORA|SABESP|DAESP|CBPM|IAMSPE|VIGILANCIA SAN|PRESIDIO|PENITENCIARI|IPESP|SUPERINTENDENCIA|D\.?E\.?R\.?\/S\.?P\.?|(^|\s)IPEM(\s|$|\-)|\\bIBAMA\\b|CDHU|COMISSAO|LICITACAO|PUBLIC[OA]|INST.*MEIO.*AMB.*REC.*NAT.*|DEP\.?(((ART)?AMEN)?(TO)?)?|MUNIC\.?(IP)?\.?(AL|IO)?|PREFEIT(O|URA)|SECRET\.?(ARI(A|O))?|MINISTERIO|CIDADE|CARTORIO|ESTADO|UNIAO|FEDERAL|AGENTE|TRANSITO|DETRAN|CORREIOS|VEREADOR|ASSEM.*LEG|COMISSAO\s?VALORES\s?MOBILIARIOS|RECEITA|PREFEIT|LICITACAO|DEPARTAMENTO|FISCAL|^OFICIO|JUIZ.*DIREITO|JUIZO|JURISDICAO|JUDICIARIO|TRIBUNAL|TJSP|DEFENSORIA|JUSTICA|CAMARA.*DIREITO|EX OFFICIO|CIRCUNSCRICAO|ELEITORAL|COMARCA|(\s|^)VARA\s|MINISTERIO PUBLICO|ERIO PUBL|PUBLICO|CIRETRAN|ARBITRAGEM|POLICIAL|2 CI|2 DRDI|AGENCIA\sNAC|PROCURADOR(I?A)?|DISTRIT|CORREGEDORIA|COORDENADORIA|JUSTICA|LEGISLATIVO|CAMARA\s(DO)?\s?MUNIC|RODAGEM|POLICIA|COMANDANTE|SUPERINT|DELEGADO',re.S)

        self.regex_cobranca = re.compile('COBRANCA|RECUP.*CREDIT',re.S)

        self.regex_pessoa_juridica_negacao = re.compile(
            'DE SA\\b')
        self.regex_banco_negacao = re.compile(
            '(\\b(SEGURADORA|PRE\sPAGO|FUNDACAO|COOP(ERATIVA)?|CONSORCIOS?|C(OMPANH)?IA\sDE\sSEGUR|PREVIDENCIA|SAUDE|SEGUROS?|TURISMO|VIDA|VENDAS?)\\b)|(UNICON|ASSOCIA|DE IMOVEIS|CAIXA DE ASSISTENCIA|COOPERATIVA|CONJUNTO DOS BANCARIOS|FUNCIONARIOS|VANDERLEI|ODETE GASPARIN|ALBERTO|BANCAMP|CARTUCHOS)')
        self.regex_pequena_empresa_negacao = re.compile(
            'LTDA')

        self.regex_governo_negacao = re.compile('COOP|SOCIEDADE|TELECOM.*VIVO|VIVO.*TELECOM|CELULAR|UNIESP|UNIMED|SIND\.?(ICATO)?')

        self.regex_cobranca_negacao = re.compile('COOP|SOCIEDADE|TELECOM.*VIVO|VIVO.*TELECOM|CELULAR|UNIESP|UNIMED|SIND\.?(ICATO)?')

    def classifica_parte_distribuicao_dict(self, parte_distibuicao_dict):
        pessoa_juridica, banco, pequena_empresa, governo, cobranca = self.classifica_parte_distribuicao(parte_distibuicao_dict["parte"])

        return self.buscar_e_salvar(parte_distibuicao_dict["id"],pessoa_juridica,banco,pequena_empresa,governo,cobranca)

    def valida(self,parte_distribuicao):
        pessoa_juridica, banco, pequena_empresa, governo, cobranca = self.classifica_parte_distribuicao(parte_distribuicao.parte)

        self.set_classificadores(parte_distribuicao,pessoa_juridica,banco,pequena_empresa,governo,cobranca)


    def classifica_parte_distribuicao(self,parte):
        pessoa_juridica = False
        banco = False
        pequena_empresa = False
        governo = False
        cobranca = False

        if self.regex_governo.search(parte) and not self.regex_governo_negacao.search(parte):
            pessoa_juridica = True
            governo = True

        elif self.regex_cobranca.search(parte):
            cobranca = True
            pessoa_juridica = True

        if ((self.regex_banco_1.search(parte) and self.regex_banco_2.search(parte)) or self.regex_banco_3.search(parte)) and not self.regex_banco_negacao.search(parte):
           pessoa_juridica = True
           banco = True

        elif self.regex_pequena_empresa.search(parte) and not self.regex_pequena_empresa_negacao.search(parte):
            pessoa_juridica = True
            pequena_empresa = True

        else:
            if (self.regex_pessoa_juridica_1.search(parte) or
                self.regex_pessoa_juridica_2.search(parte) or
                self.regex_pessoa_juridica_3.search(parte) or
                self.regex_pessoa_juridica_4.search(parte)) and not \
                    self.regex_pessoa_juridica_negacao.search(parte):
                pessoa_juridica = True

        return pessoa_juridica,banco,pequena_empresa,governo,cobranca

    def buscar_e_salvar(self,id,pessoa_juridica,banco,pequena_empresa,governo,cobranca):
        if  pessoa_juridica or banco or pequena_empresa or governo or cobranca:
            parte_distribuicao = self.parte_distribuicao_dao.get_por_id(id)
            parte_distribuicao.parte = parte_distribuicao.parte
            self.set_classificadores(parte_distribuicao,pessoa_juridica,banco,pequena_empresa,governo,cobranca)

            return [parte_distribuicao]
        return []

    def set_classificadores(self,parte_distribuicao,pessoa_juridica,banco,pequena_empresa,governo,cobranca):
        if  pessoa_juridica or banco or pequena_empresa or governo or cobranca:
            parte_distribuicao.pessoa_juridica = pessoa_juridica
            parte_distribuicao.banco = banco
            parte_distribuicao.pequena_empresa = pequena_empresa
            parte_distribuicao.governo = governo
            parte_distribuicao.cobranca = cobranca

    def extrai_parte_distribuicao(self,linha):
        lista = linha.split("\t")

        parte_distribuicao = {}

        for i,item in enumerate(lista):
            if i == 1:
                parte_distribuicao["id"] = item
            if i == 3:
                parte_distribuicao["parte"] = item
        return parte_distribuicao

    def valida_arquivo(self,caminho):

        arq = open(caminho)

        i= 1
        start_time = time.time()
        tempo_atual = 0
        partes =[]

        while True:

            linha = arq.readline()

            if not linha:
                self.parte_distribuicao_dao.commit()
                return

            parte_distribuicao = self.extrai_parte_distribuicao(linha)

            #print(parte_distribuicao['parte'])
            partes.extend(self.classifica_parte_distribuicao_dict(parte_distribuicao))

            if len(partes) >= 5000:
                self.parte_distribuicao_dao.salvar_lote(partes,salvar_estrangeiras=False,salvar_many_to_many=False)
                partes = []

            if i % 1000000 == 0:
                tempo_passado = tempo_atual
                tempo_atual = (time.time() - start_time)
                print("Exectuado em {} milhões de linhas".format(str(i/1000000)))
                print("--- tempo total:  %s segundos ---" % (time.time() - start_time))
                print("--- tempo atual:  %s segundos ---" % str(abs(tempo_passado - tempo_atual)))

            i+=1




if __name__ == '__main__':
    if len(sys.argv) > 1:
        ClassificaParteDistribuicao().valida_arquivo("C://Users//b13001972777//partedistribuicao/parte_distribuicao-{}.csv".format(sys.argv[1]))
    else:
        ClassificaParteDistribuicao().valida_arquivo("C://Users//b13001972777//parte_distribuicao.csv")